from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('products/', views.product_list, name='product_list'),
    path('search/', views.product_list, name='search'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/<int:pk>/review/', views.review_product, name='review_product'),
    path('product/<int:pk>/review/delete/', views.delete_review, name='delete_review'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:pk>/', views.cart_add, name='cart_add'),
    path('cart/update/<int:pk>/', views.cart_update, name='cart_update'),
    path('cart/remove/<int:pk>/', views.cart_remove, name='cart_remove'),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('wishlist/toggle/<int:pk>/', views.wishlist_toggle, name='wishlist_toggle'),
    path('wishlist/move/<int:pk>/', views.wishlist_move_to_cart, name='wishlist_move_to_cart'),
    path('coupon/apply/', views.apply_coupon, name='apply_coupon'),
    path('coupon/remove/', views.remove_coupon, name='remove_coupon'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('order/confirmation/<str:order_number>/', views.order_confirmation, name='order_confirmation'),
    path('orders/', views.my_orders, name='my_orders'),
    path('orders/<str:order_number>/', views.order_detail, name='order_detail'),
    path('orders/<str:order_number>/track/', views.order_tracking, name='order_tracking'),
    path('orders/<str:order_number>/cancel/', views.cancel_order, name='cancel_order'),
    path('addresses/', views.address_management, name='addresses'),
    path('addresses/delete/<int:pk>/', views.delete_address, name='delete_address'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/read-all/', views.mark_notifications_read, name='mark_notifications_read'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/products/', views.admin_products, name='admin_products'),
    path('admin-dashboard/categories/', views.admin_categories, name='admin_categories'),
    path('admin-dashboard/orders/', views.admin_orders, name='admin_orders'),
    path('admin-dashboard/users/', views.admin_users, name='admin_users'),
    path('admin-dashboard/coupons/', views.admin_coupons, name='admin_coupons'),
]
